### ISSUE TITLE
Support more than one channel

### ISSUE THREAD

**Issue by M1dgard** [UlfS/ghmm#16]
I have to relay messages to different channels based on which repo they originate from. As far as I can see, this is not yet possible apart from starting this program multiple times.

Some configuration file like this would make a lot of sense to me:
```yaml
# Server config
address: 0.0.0.0
port: 8000

# Defaults
prefix: /hooks/github_hooks
username: GitHub announcer
icon_url: https://example.com/github_logo.png

# Per-repo config
repos:
    some_org/one_repo:
        channel: one
        secret: CF…
    another_org:
        channel: another-org-devs
        secret: pQ…
        username: Da GitHub man
        icon_url: https://example.com/github_special_logo.png
    another_org:
        channel: another-org-support
        secret: jf…
        prefix: /hooks/github_hooks_support

# Ignore certain events
ignore:
    issues:
        - labeled
    pull_request:
        - labeled
        - assigned
```
This example is written in YAML.
