### ISSUE TITLE
Ignoring certain events

### ISSUE THREAD

**Issue by ghost** [UlfS/ghmm#18]
For example in a configuration file:

```yaml
ignore:
    issues:
        - labeled
    pull_request:
        - labeled
        - assigned
```

would prevent sending notifications for the labeling of issues and for the labeling and assigning of PRs.
